/**
 * National government careers abroad. Each entry maps a US federal career
 * (the template whose ladder, pay grades and events it reuses) to the
 * country's real counterpart: { name, employers, titles? }. JobTrees.js
 * builds the professions (id `${cc}_${template}`, e.g. `ca_fbi`); they are
 * open only to that country's citizens living there.
 *
 * `titles` renames ladder levels where the country's ranks differ.
 */

const POLICE_INVESTIGATOR = { trainee: 'Trainee Investigator', agent: 'Investigator', senior: 'Senior Investigator', ssa: 'Team Leader', asac: 'Unit Commander', sac: 'Director' };

export const AGENCIES = {
  CA: {
    fbi: { name: 'Royal Canadian Mounted Police', employers: ['RCMP — Federal Policing', 'RCMP — Major Crime Unit'], titles: { trainee: 'Cadet (Depot Division)', agent: 'Constable', senior: 'Corporal', ssa: 'Sergeant', asac: 'Inspector', sac: 'Chief Superintendent' } },
    usss: { name: 'RCMP Protective Policing', employers: ['RCMP — Protective Policing'], titles: { trainee: 'Cadet (Depot Division)', agent: 'Constable', senior: 'Corporal', ssa: 'Sergeant', asac: 'Inspector', sac: 'Chief Superintendent' } },
    borderPatrol: { name: 'Canada Border Services Agency', employers: ['CBSA — Port of Entry', 'CBSA — Inland Enforcement'] },
    tsa: { name: 'CATSA Screening', employers: ['CATSA — Toronto Pearson', 'CATSA — Vancouver International'] },
    federalPrisons: { name: 'Correctional Service Canada', employers: ['CSC — Millhaven Institution', 'CSC — Kent Institution'] },
    postal: { name: 'Canada Post', employers: ['Canada Post — Delivery Depot'] },
    benefitsClaims: { name: 'Service Canada', employers: ['Service Canada Centre'] },
    caseOfficer: { name: 'CSIS Intelligence Officer', employers: ['Canadian Security Intelligence Service'] },
    sigint: { name: 'Communications Security Establishment', employers: ['CSE — Ottawa'] },
    intelligence: { name: 'Intelligence Analysis (CSIS · PCO)', employers: ['CSIS Intelligence Assessments', 'Privy Council Office'] },
    meteorology: { name: 'Meteorological Service of Canada', employers: ['Environment and Climate Change Canada'] },
    regulatory: { name: 'Federal Regulator (OSFI · CRA)', employers: ['Office of the Superintendent of Financial Institutions', 'Canada Revenue Agency'] },
    foreignService: { name: 'Global Affairs Canada', employers: ['Global Affairs Canada'] },
    parkService: { name: 'Parks Canada', employers: ['Banff National Park', 'Jasper National Park'] },
    airTrafficControl: { name: 'NAV CANADA', employers: ['NAV CANADA — Toronto Area Control Centre'] },
    nationalLab: { name: 'National Research Council Canada', employers: ['NRC — Ottawa'] },
    oig: { name: 'Office of the Auditor General', employers: ['Auditor General of Canada'] },
  },
  GB: {
    fbi: { name: 'National Crime Agency', employers: ['NCA — Investigations', 'NCA — Organised Crime'], titles: { trainee: 'Trainee NCA Officer', agent: 'NCA Officer', senior: 'Senior NCA Officer', ssa: 'Team Leader', asac: 'Branch Commander', sac: 'Director' } },
    usss: { name: 'Royalty and Specialist Protection', employers: ['Metropolitan Police — Protection Command'], titles: { trainee: 'Probationary Constable', agent: 'Protection Officer', senior: 'Detective Sergeant', ssa: 'Detective Inspector', asac: 'Chief Inspector', sac: 'Commander' } },
    borderPatrol: { name: 'UK Border Force', employers: ['Border Force — Heathrow', 'Border Force — Dover'] },
    federalPrisons: { name: 'HM Prison and Probation Service', employers: ['HMP Wandsworth', 'HMP Manchester'] },
    postal: { name: 'Royal Mail', employers: ['Royal Mail Delivery Office'] },
    benefitsClaims: { name: 'Department for Work and Pensions', employers: ['Jobcentre Plus', 'The Pension Service'] },
    caseOfficer: { name: 'Secret Intelligence Service (MI6)', employers: ['SIS — Vauxhall Cross'] },
    sigint: { name: 'GCHQ', employers: ['GCHQ — Cheltenham'] },
    intelligence: { name: 'Security Service (MI5)', employers: ['MI5 — Thames House'] },
    meteorology: { name: 'Met Office', employers: ['Met Office — Exeter'] },
    regulatory: { name: 'Financial Regulation (FCA · HMRC)', employers: ['Financial Conduct Authority', 'HM Revenue & Customs'] },
    foreignService: { name: 'Foreign, Commonwealth & Development Office', employers: ['FCDO — King Charles Street'] },
    parkService: { name: 'National Park Ranger', employers: ['Lake District National Park', 'Peak District National Park'] },
    airTrafficControl: { name: 'NATS Air Traffic Control', employers: ['NATS — Swanwick'] },
    nationalLab: { name: 'UKRI Research Institutes', employers: ['Rutherford Appleton Laboratory'] },
    oig: { name: 'National Audit Office', employers: ['National Audit Office'] },
  },
  DE: {
    fbi: { name: 'Bundeskriminalamt (BKA)', employers: ['BKA — Wiesbaden', 'BKA — Berlin'], titles: { trainee: 'Kriminalkommissaranwärter', agent: 'Kriminalkommissar', senior: 'Kriminaloberkommissar', ssa: 'Kriminalhauptkommissar', asac: 'Kriminalrat', sac: 'Kriminaldirektor' } },
    usss: { name: 'BKA Sicherungsgruppe', employers: ['BKA — Sicherungsgruppe'], titles: { trainee: 'Kommissaranwärter', agent: 'Kommissar', senior: 'Oberkommissar', ssa: 'Hauptkommissar', asac: 'Polizeirat', sac: 'Polizeidirektor' } },
    borderPatrol: { name: 'Bundespolizei', employers: ['Bundespolizei — Flughafen Frankfurt', 'Bundespolizei — Grenzschutz'] },
    tsa: { name: 'Luftsicherheit (Bundespolizei)', employers: ['Luftsicherheit — Frankfurt Airport'] },
    postal: { name: 'Deutsche Post', employers: ['Deutsche Post — Zustellbasis'] },
    benefitsClaims: { name: 'Bundesagentur für Arbeit / Rentenversicherung', employers: ['Jobcenter', 'Deutsche Rentenversicherung'] },
    caseOfficer: { name: 'Bundesnachrichtendienst (BND)', employers: ['BND — Pullach'] },
    sigint: { name: 'BND Technical Reconnaissance', employers: ['BND — Bad Aibling'] },
    intelligence: { name: 'Bundesamt für Verfassungsschutz', employers: ['BfV — Köln'] },
    meteorology: { name: 'Deutscher Wetterdienst', employers: ['DWD — Offenbach'] },
    regulatory: { name: 'BaFin', employers: ['BaFin — Bonn', 'Bundeskartellamt'] },
    foreignService: { name: 'Auswärtiges Amt', employers: ['Auswärtiges Amt — Berlin'] },
    airTrafficControl: { name: 'DFS Deutsche Flugsicherung', employers: ['DFS — Langen'] },
    nationalLab: { name: 'Max Planck & Helmholtz Research', employers: ['Max-Planck-Institut', 'Deutsches Zentrum für Luft- und Raumfahrt'] },
    oig: { name: 'Bundesrechnungshof', employers: ['Bundesrechnungshof — Bonn'] },
  },
  JP: {
    fbi: { name: 'National Police Agency', employers: ['NPA — Kasumigaseki'], titles: { trainee: 'Police Academy Trainee', agent: 'Assistant Inspector', senior: 'Inspector', ssa: 'Superintendent', asac: 'Senior Superintendent', sac: 'Chief Superintendent' } },
    usss: { name: 'Imperial Guard', employers: ['Imperial Guard Headquarters'] },
    borderPatrol: { name: 'Japan Coast Guard', employers: ['JCG — 3rd Regional Headquarters'] },
    federalPrisons: { name: 'Correction Bureau (Ministry of Justice)', employers: ['Fuchu Prison', 'Osaka Prison'] },
    postal: { name: 'Japan Post', employers: ['Japan Post — Delivery Office'] },
    benefitsClaims: { name: 'Japan Pension Service', employers: ['Nenkin Jimusho'] },
    sigint: { name: 'Cabinet Satellite Intelligence Center', employers: ['CSICE — Tokyo'] },
    intelligence: { name: 'Public Security Intelligence Agency', employers: ['PSIA — Tokyo'] },
    meteorology: { name: 'Japan Meteorological Agency', employers: ['JMA — Tokyo'] },
    regulatory: { name: 'Financial Services Agency', employers: ['FSA — Tokyo'] },
    foreignService: { name: 'Ministry of Foreign Affairs', employers: ['MOFA — Kasumigaseki'] },
    parkService: { name: 'National Park Ranger (Ministry of the Environment)', employers: ['Nikko National Park', 'Fuji-Hakone-Izu National Park'] },
    airTrafficControl: { name: 'JCAB Air Traffic Control', employers: ['Tokyo Area Control Center'] },
    nationalLab: { name: 'RIKEN & JAXA', employers: ['RIKEN', 'JAXA — Tsukuba'] },
  },
  KR: {
    fbi: { name: 'National Investigation Headquarters (KNPA)', employers: ['KNPA — National Investigation HQ'], titles: POLICE_INVESTIGATOR },
    usss: { name: 'Presidential Security Service', employers: ['Presidential Security Service'] },
    borderPatrol: { name: 'Korea Coast Guard', employers: ['KCG — Incheon'] },
    federalPrisons: { name: 'Korea Correctional Service', employers: ['Seoul Detention Center'] },
    postal: { name: 'Korea Post', employers: ['Korea Post — Delivery'] },
    benefitsClaims: { name: 'National Pension Service', employers: ['NPS — Branch Office'] },
    caseOfficer: { name: 'National Intelligence Service', employers: ['NIS — Naegok-dong'] },
    intelligence: { name: 'NIS Analysis Directorate', employers: ['NIS — Naegok-dong'] },
    meteorology: { name: 'Korea Meteorological Administration', employers: ['KMA — Seoul'] },
    regulatory: { name: 'Financial Supervisory Service', employers: ['FSS — Yeouido'] },
    foreignService: { name: 'Ministry of Foreign Affairs', employers: ['MOFA — Seoul'] },
    airTrafficControl: { name: 'Incheon Area Control Center', employers: ['Incheon ACC'] },
    nationalLab: { name: 'KIST & KAIST Research', employers: ['Korea Institute of Science and Technology'] },
  },
  IT: {
    fbi: { name: 'Polizia di Stato (Squadra Mobile)', employers: ['Questura di Roma', 'Questura di Milano'], titles: { trainee: 'Allievo Agente', agent: 'Agente', senior: 'Ispettore', ssa: 'Commissario', asac: 'Vice Questore', sac: 'Questore' } },
    usms: { name: 'Arma dei Carabinieri', employers: ['Comando Provinciale Carabinieri'], titles: { trainee: 'Allievo Carabiniere', agent: 'Carabiniere', senior: 'Brigadiere', ssa: 'Maresciallo', asac: 'Capitano', sac: 'Colonnello' } },
    borderPatrol: { name: 'Guardia di Finanza', employers: ['Comando Provinciale Guardia di Finanza'] },
    federalPrisons: { name: 'Polizia Penitenziaria', employers: ['Casa Circondariale di Rebibbia'] },
    postal: { name: 'Poste Italiane', employers: ['Poste Italiane — Centro di Recapito'] },
    benefitsClaims: { name: 'INPS', employers: ['INPS — Sede Provinciale'] },
    caseOfficer: { name: 'AISE (foreign intelligence)', employers: ['AISE — Forte Braschi'] },
    intelligence: { name: 'AISI (domestic intelligence)', employers: ['AISI — Rome'] },
    meteorology: { name: 'Servizio Meteorologico (Aeronautica Militare)', employers: ['Centro Operativo Meteo — Pratica di Mare'] },
    regulatory: { name: 'CONSOB / Banca d\'Italia', employers: ['CONSOB', 'Banca d\'Italia'] },
    foreignService: { name: 'Farnesina (MAECI)', employers: ['Ministero degli Affari Esteri'] },
    airTrafficControl: { name: 'ENAV', employers: ['ENAV — Area Control Centre Roma'] },
    nationalLab: { name: 'CNR & INFN Research', employers: ['Consiglio Nazionale delle Ricerche'] },
  },
  MX: {
    fbi: { name: 'Fiscalía General de la República (AIC)', employers: ['FGR — Agencia de Investigación Criminal'], titles: POLICE_INVESTIGATOR },
    borderPatrol: { name: 'Guardia Nacional', employers: ['Guardia Nacional — Coordinación Estatal'] },
    usss: { name: 'Presidential Security (Ayudantía)', employers: ['Ayudantía de la Presidencia'] },
    federalPrisons: { name: 'Prevención y Readaptación Social', employers: ['CEFERESO No. 1 Altiplano'] },
    postal: { name: 'Correos de México', employers: ['Correos de México — Centro de Distribución'] },
    benefitsClaims: { name: 'IMSS', employers: ['IMSS — Subdelegación'] },
    caseOfficer: { name: 'Centro Nacional de Inteligencia', employers: ['CNI — Mexico City'] },
    intelligence: { name: 'CNI Analysis', employers: ['CNI — Mexico City'] },
    meteorology: { name: 'Servicio Meteorológico Nacional', employers: ['SMN — CONAGUA'] },
    regulatory: { name: 'CNBV / SAT', employers: ['Comisión Nacional Bancaria y de Valores', 'Servicio de Administración Tributaria'] },
    foreignService: { name: 'Servicio Exterior Mexicano (SRE)', employers: ['Secretaría de Relaciones Exteriores'] },
    airTrafficControl: { name: 'SENEAM', employers: ['SENEAM — Centro de Control México'] },
    nationalLab: { name: 'CINVESTAV', employers: ['CINVESTAV — Zacatenco'] },
  },
  PH: {
    fbi: { name: 'National Bureau of Investigation', employers: ['NBI — Manila'], titles: { trainee: 'Agent Trainee', agent: 'Special Investigator', senior: 'Senior Agent', ssa: 'Supervising Agent', asac: 'Assistant Regional Director', sac: 'Regional Director' } },
    dea: { name: 'Philippine Drug Enforcement Agency', employers: ['PDEA — Regional Office'] },
    usss: { name: 'Presidential Security Command', employers: ['PSC — Malacañang'] },
    borderPatrol: { name: 'Bureau of Immigration', employers: ['BI — NAIA'] },
    federalPrisons: { name: 'Bureau of Corrections', employers: ['New Bilibid Prison'] },
    postal: { name: 'PHLPost', employers: ['PHLPost — Manila Central'] },
    benefitsClaims: { name: 'SSS / GSIS', employers: ['Social Security System — Branch'] },
    caseOfficer: { name: 'National Intelligence Coordinating Agency', employers: ['NICA — Quezon City'] },
    meteorology: { name: 'PAGASA', employers: ['PAGASA — Quezon City'] },
    regulatory: { name: 'Bangko Sentral / SEC', employers: ['Bangko Sentral ng Pilipinas', 'Securities and Exchange Commission'] },
    foreignService: { name: 'Department of Foreign Affairs', employers: ['DFA — Pasay'] },
    airTrafficControl: { name: 'CAAP Air Traffic Service', employers: ['CAAP — Manila ACC'] },
    parkService: { name: 'DENR Protected Areas', employers: ['Puerto Princesa Underground River', 'Mount Apo Natural Park'] },
  },
  IN: {
    fbi: { name: 'Central Bureau of Investigation', employers: ['CBI — New Delhi'], titles: { trainee: 'Sub-Inspector (trainee)', agent: 'Sub-Inspector', senior: 'Inspector', ssa: 'Deputy Superintendent', asac: 'Superintendent of Police', sac: 'Deputy Inspector General' } },
    dea: { name: 'Narcotics Control Bureau', employers: ['NCB — Zonal Unit'] },
    usms: { name: 'Central Reserve Police Force', employers: ['CRPF — Battalion'] },
    usss: { name: 'Special Protection Group', employers: ['SPG — New Delhi'] },
    borderPatrol: { name: 'Border Security Force', employers: ['BSF — Frontier HQ'] },
    tsa: { name: 'CISF Aviation Security', employers: ['CISF — Delhi Airport'] },
    federalPrisons: { name: 'Tihar Prisons', employers: ['Tihar Jail'] },
    postal: { name: 'India Post', employers: ['India Post — Head Post Office'] },
    benefitsClaims: { name: 'EPFO', employers: ['EPFO — Regional Office'] },
    caseOfficer: { name: 'Research and Analysis Wing (R&AW)', employers: ['R&AW — CGO Complex'] },
    intelligence: { name: 'Intelligence Bureau', employers: ['IB — New Delhi'] },
    sigint: { name: 'National Technical Research Organisation', employers: ['NTRO — New Delhi'] },
    meteorology: { name: 'India Meteorological Department', employers: ['IMD — New Delhi'] },
    regulatory: { name: 'SEBI / RBI', employers: ['Securities and Exchange Board of India', 'Reserve Bank of India'] },
    foreignService: { name: 'Indian Foreign Service (MEA)', employers: ['Ministry of External Affairs'] },
    airTrafficControl: { name: 'Airports Authority of India ATC', employers: ['AAI — Delhi ACC'] },
    nationalLab: { name: 'ISRO & DRDO', employers: ['ISRO — Bengaluru', 'DRDO — New Delhi'] },
  },
};

export const nationalProfessionId = (countryId, templateId) => `${countryId.toLowerCase()}_${templateId}`;
